// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/publication.proto

package models.publication;

public final class PublicationOuterClass {
  private PublicationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PublicationFieldOrBuilder extends
      // @@protoc_insertion_point(interface_extends:models.publication.PublicationField)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string fieldName = 1;</code>
     * @return The fieldName.
     */
    java.lang.String getFieldName();
    /**
     * <code>string fieldName = 1;</code>
     * @return The bytes for fieldName.
     */
    com.google.protobuf.ByteString
        getFieldNameBytes();

    /**
     * <code>string companyField = 2;</code>
     * @return The companyField.
     */
    java.lang.String getCompanyField();
    /**
     * <code>string companyField = 2;</code>
     * @return The bytes for companyField.
     */
    com.google.protobuf.ByteString
        getCompanyFieldBytes();

    /**
     * <code>double valueField = 3;</code>
     * @return The valueField.
     */
    double getValueField();

    /**
     * <code>double dropField = 4;</code>
     * @return The dropField.
     */
    double getDropField();

    /**
     * <code>double variationField = 5;</code>
     * @return The variationField.
     */
    double getVariationField();

    /**
     * <code>string dateField = 6;</code>
     * @return The dateField.
     */
    java.lang.String getDateField();
    /**
     * <code>string dateField = 6;</code>
     * @return The bytes for dateField.
     */
    com.google.protobuf.ByteString
        getDateFieldBytes();

    public models.publication.PublicationOuterClass.PublicationField.ValueCase getValueCase();
  }
  /**
   * Protobuf type {@code models.publication.PublicationField}
   */
  public static final class PublicationField extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:models.publication.PublicationField)
      PublicationFieldOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PublicationField.newBuilder() to construct.
    private PublicationField(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PublicationField() {
      fieldName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PublicationField();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PublicationField(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fieldName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              valueCase_ = 2;
              value_ = s;
              break;
            }
            case 25: {
              valueCase_ = 3;
              value_ = input.readDouble();
              break;
            }
            case 33: {
              valueCase_ = 4;
              value_ = input.readDouble();
              break;
            }
            case 41: {
              valueCase_ = 5;
              value_ = input.readDouble();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              valueCase_ = 6;
              value_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return models.publication.PublicationOuterClass.internal_static_models_publication_PublicationField_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return models.publication.PublicationOuterClass.internal_static_models_publication_PublicationField_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              models.publication.PublicationOuterClass.PublicationField.class, models.publication.PublicationOuterClass.PublicationField.Builder.class);
    }

    private int valueCase_ = 0;
    private java.lang.Object value_;
    public enum ValueCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      COMPANYFIELD(2),
      VALUEFIELD(3),
      DROPFIELD(4),
      VARIATIONFIELD(5),
      DATEFIELD(6),
      VALUE_NOT_SET(0);
      private final int value;
      private ValueCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueCase valueOf(int value) {
        return forNumber(value);
      }

      public static ValueCase forNumber(int value) {
        switch (value) {
          case 2: return COMPANYFIELD;
          case 3: return VALUEFIELD;
          case 4: return DROPFIELD;
          case 5: return VARIATIONFIELD;
          case 6: return DATEFIELD;
          case 0: return VALUE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ValueCase
    getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public static final int FIELDNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object fieldName_;
    /**
     * <code>string fieldName = 1;</code>
     * @return The fieldName.
     */
    @java.lang.Override
    public java.lang.String getFieldName() {
      java.lang.Object ref = fieldName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fieldName_ = s;
        return s;
      }
    }
    /**
     * <code>string fieldName = 1;</code>
     * @return The bytes for fieldName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFieldNameBytes() {
      java.lang.Object ref = fieldName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fieldName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANYFIELD_FIELD_NUMBER = 2;
    /**
     * <code>string companyField = 2;</code>
     * @return The companyField.
     */
    public java.lang.String getCompanyField() {
      java.lang.Object ref = "";
      if (valueCase_ == 2) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valueCase_ == 2) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string companyField = 2;</code>
     * @return The bytes for companyField.
     */
    public com.google.protobuf.ByteString
        getCompanyFieldBytes() {
      java.lang.Object ref = "";
      if (valueCase_ == 2) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueCase_ == 2) {
          value_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUEFIELD_FIELD_NUMBER = 3;
    /**
     * <code>double valueField = 3;</code>
     * @return The valueField.
     */
    @java.lang.Override
    public double getValueField() {
      if (valueCase_ == 3) {
        return (java.lang.Double) value_;
      }
      return 0D;
    }

    public static final int DROPFIELD_FIELD_NUMBER = 4;
    /**
     * <code>double dropField = 4;</code>
     * @return The dropField.
     */
    @java.lang.Override
    public double getDropField() {
      if (valueCase_ == 4) {
        return (java.lang.Double) value_;
      }
      return 0D;
    }

    public static final int VARIATIONFIELD_FIELD_NUMBER = 5;
    /**
     * <code>double variationField = 5;</code>
     * @return The variationField.
     */
    @java.lang.Override
    public double getVariationField() {
      if (valueCase_ == 5) {
        return (java.lang.Double) value_;
      }
      return 0D;
    }

    public static final int DATEFIELD_FIELD_NUMBER = 6;
    /**
     * <code>string dateField = 6;</code>
     * @return The dateField.
     */
    public java.lang.String getDateField() {
      java.lang.Object ref = "";
      if (valueCase_ == 6) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valueCase_ == 6) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string dateField = 6;</code>
     * @return The bytes for dateField.
     */
    public com.google.protobuf.ByteString
        getDateFieldBytes() {
      java.lang.Object ref = "";
      if (valueCase_ == 6) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueCase_ == 6) {
          value_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFieldNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fieldName_);
      }
      if (valueCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      if (valueCase_ == 3) {
        output.writeDouble(
            3, (double)((java.lang.Double) value_));
      }
      if (valueCase_ == 4) {
        output.writeDouble(
            4, (double)((java.lang.Double) value_));
      }
      if (valueCase_ == 5) {
        output.writeDouble(
            5, (double)((java.lang.Double) value_));
      }
      if (valueCase_ == 6) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFieldNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fieldName_);
      }
      if (valueCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      if (valueCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(
              3, (double)((java.lang.Double) value_));
      }
      if (valueCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(
              4, (double)((java.lang.Double) value_));
      }
      if (valueCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(
              5, (double)((java.lang.Double) value_));
      }
      if (valueCase_ == 6) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof models.publication.PublicationOuterClass.PublicationField)) {
        return super.equals(obj);
      }
      models.publication.PublicationOuterClass.PublicationField other = (models.publication.PublicationOuterClass.PublicationField) obj;

      if (!getFieldName()
          .equals(other.getFieldName())) return false;
      if (!getValueCase().equals(other.getValueCase())) return false;
      switch (valueCase_) {
        case 2:
          if (!getCompanyField()
              .equals(other.getCompanyField())) return false;
          break;
        case 3:
          if (java.lang.Double.doubleToLongBits(getValueField())
              != java.lang.Double.doubleToLongBits(
                  other.getValueField())) return false;
          break;
        case 4:
          if (java.lang.Double.doubleToLongBits(getDropField())
              != java.lang.Double.doubleToLongBits(
                  other.getDropField())) return false;
          break;
        case 5:
          if (java.lang.Double.doubleToLongBits(getVariationField())
              != java.lang.Double.doubleToLongBits(
                  other.getVariationField())) return false;
          break;
        case 6:
          if (!getDateField()
              .equals(other.getDateField())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIELDNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFieldName().hashCode();
      switch (valueCase_) {
        case 2:
          hash = (37 * hash) + COMPANYFIELD_FIELD_NUMBER;
          hash = (53 * hash) + getCompanyField().hashCode();
          break;
        case 3:
          hash = (37 * hash) + VALUEFIELD_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              java.lang.Double.doubleToLongBits(getValueField()));
          break;
        case 4:
          hash = (37 * hash) + DROPFIELD_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              java.lang.Double.doubleToLongBits(getDropField()));
          break;
        case 5:
          hash = (37 * hash) + VARIATIONFIELD_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              java.lang.Double.doubleToLongBits(getVariationField()));
          break;
        case 6:
          hash = (37 * hash) + DATEFIELD_FIELD_NUMBER;
          hash = (53 * hash) + getDateField().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static models.publication.PublicationOuterClass.PublicationField parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static models.publication.PublicationOuterClass.PublicationField parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static models.publication.PublicationOuterClass.PublicationField parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static models.publication.PublicationOuterClass.PublicationField parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static models.publication.PublicationOuterClass.PublicationField parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static models.publication.PublicationOuterClass.PublicationField parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static models.publication.PublicationOuterClass.PublicationField parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static models.publication.PublicationOuterClass.PublicationField parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static models.publication.PublicationOuterClass.PublicationField parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static models.publication.PublicationOuterClass.PublicationField parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static models.publication.PublicationOuterClass.PublicationField parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static models.publication.PublicationOuterClass.PublicationField parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(models.publication.PublicationOuterClass.PublicationField prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code models.publication.PublicationField}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:models.publication.PublicationField)
        models.publication.PublicationOuterClass.PublicationFieldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return models.publication.PublicationOuterClass.internal_static_models_publication_PublicationField_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return models.publication.PublicationOuterClass.internal_static_models_publication_PublicationField_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                models.publication.PublicationOuterClass.PublicationField.class, models.publication.PublicationOuterClass.PublicationField.Builder.class);
      }

      // Construct using models.publication.PublicationOuterClass.PublicationField.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fieldName_ = "";

        valueCase_ = 0;
        value_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return models.publication.PublicationOuterClass.internal_static_models_publication_PublicationField_descriptor;
      }

      @java.lang.Override
      public models.publication.PublicationOuterClass.PublicationField getDefaultInstanceForType() {
        return models.publication.PublicationOuterClass.PublicationField.getDefaultInstance();
      }

      @java.lang.Override
      public models.publication.PublicationOuterClass.PublicationField build() {
        models.publication.PublicationOuterClass.PublicationField result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public models.publication.PublicationOuterClass.PublicationField buildPartial() {
        models.publication.PublicationOuterClass.PublicationField result = new models.publication.PublicationOuterClass.PublicationField(this);
        result.fieldName_ = fieldName_;
        if (valueCase_ == 2) {
          result.value_ = value_;
        }
        if (valueCase_ == 3) {
          result.value_ = value_;
        }
        if (valueCase_ == 4) {
          result.value_ = value_;
        }
        if (valueCase_ == 5) {
          result.value_ = value_;
        }
        if (valueCase_ == 6) {
          result.value_ = value_;
        }
        result.valueCase_ = valueCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof models.publication.PublicationOuterClass.PublicationField) {
          return mergeFrom((models.publication.PublicationOuterClass.PublicationField)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(models.publication.PublicationOuterClass.PublicationField other) {
        if (other == models.publication.PublicationOuterClass.PublicationField.getDefaultInstance()) return this;
        if (!other.getFieldName().isEmpty()) {
          fieldName_ = other.fieldName_;
          onChanged();
        }
        switch (other.getValueCase()) {
          case COMPANYFIELD: {
            valueCase_ = 2;
            value_ = other.value_;
            onChanged();
            break;
          }
          case VALUEFIELD: {
            setValueField(other.getValueField());
            break;
          }
          case DROPFIELD: {
            setDropField(other.getDropField());
            break;
          }
          case VARIATIONFIELD: {
            setVariationField(other.getVariationField());
            break;
          }
          case DATEFIELD: {
            valueCase_ = 6;
            value_ = other.value_;
            onChanged();
            break;
          }
          case VALUE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        models.publication.PublicationOuterClass.PublicationField parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (models.publication.PublicationOuterClass.PublicationField) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int valueCase_ = 0;
      private java.lang.Object value_;
      public ValueCase
          getValueCase() {
        return ValueCase.forNumber(
            valueCase_);
      }

      public Builder clearValue() {
        valueCase_ = 0;
        value_ = null;
        onChanged();
        return this;
      }


      private java.lang.Object fieldName_ = "";
      /**
       * <code>string fieldName = 1;</code>
       * @return The fieldName.
       */
      public java.lang.String getFieldName() {
        java.lang.Object ref = fieldName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fieldName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fieldName = 1;</code>
       * @return The bytes for fieldName.
       */
      public com.google.protobuf.ByteString
          getFieldNameBytes() {
        java.lang.Object ref = fieldName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fieldName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fieldName = 1;</code>
       * @param value The fieldName to set.
       * @return This builder for chaining.
       */
      public Builder setFieldName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fieldName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fieldName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFieldName() {
        
        fieldName_ = getDefaultInstance().getFieldName();
        onChanged();
        return this;
      }
      /**
       * <code>string fieldName = 1;</code>
       * @param value The bytes for fieldName to set.
       * @return This builder for chaining.
       */
      public Builder setFieldNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fieldName_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string companyField = 2;</code>
       * @return The companyField.
       */
      @java.lang.Override
      public java.lang.String getCompanyField() {
        java.lang.Object ref = "";
        if (valueCase_ == 2) {
          ref = value_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (valueCase_ == 2) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string companyField = 2;</code>
       * @return The bytes for companyField.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCompanyFieldBytes() {
        java.lang.Object ref = "";
        if (valueCase_ == 2) {
          ref = value_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (valueCase_ == 2) {
            value_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string companyField = 2;</code>
       * @param value The companyField to set.
       * @return This builder for chaining.
       */
      public Builder setCompanyField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 2;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string companyField = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompanyField() {
        if (valueCase_ == 2) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string companyField = 2;</code>
       * @param value The bytes for companyField to set.
       * @return This builder for chaining.
       */
      public Builder setCompanyFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        valueCase_ = 2;
        value_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>double valueField = 3;</code>
       * @return The valueField.
       */
      public double getValueField() {
        if (valueCase_ == 3) {
          return (java.lang.Double) value_;
        }
        return 0D;
      }
      /**
       * <code>double valueField = 3;</code>
       * @param value The valueField to set.
       * @return This builder for chaining.
       */
      public Builder setValueField(double value) {
        valueCase_ = 3;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double valueField = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValueField() {
        if (valueCase_ == 3) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>double dropField = 4;</code>
       * @return The dropField.
       */
      public double getDropField() {
        if (valueCase_ == 4) {
          return (java.lang.Double) value_;
        }
        return 0D;
      }
      /**
       * <code>double dropField = 4;</code>
       * @param value The dropField to set.
       * @return This builder for chaining.
       */
      public Builder setDropField(double value) {
        valueCase_ = 4;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double dropField = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDropField() {
        if (valueCase_ == 4) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>double variationField = 5;</code>
       * @return The variationField.
       */
      public double getVariationField() {
        if (valueCase_ == 5) {
          return (java.lang.Double) value_;
        }
        return 0D;
      }
      /**
       * <code>double variationField = 5;</code>
       * @param value The variationField to set.
       * @return This builder for chaining.
       */
      public Builder setVariationField(double value) {
        valueCase_ = 5;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double variationField = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearVariationField() {
        if (valueCase_ == 5) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>string dateField = 6;</code>
       * @return The dateField.
       */
      @java.lang.Override
      public java.lang.String getDateField() {
        java.lang.Object ref = "";
        if (valueCase_ == 6) {
          ref = value_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (valueCase_ == 6) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dateField = 6;</code>
       * @return The bytes for dateField.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDateFieldBytes() {
        java.lang.Object ref = "";
        if (valueCase_ == 6) {
          ref = value_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (valueCase_ == 6) {
            value_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dateField = 6;</code>
       * @param value The dateField to set.
       * @return This builder for chaining.
       */
      public Builder setDateField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 6;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dateField = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDateField() {
        if (valueCase_ == 6) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string dateField = 6;</code>
       * @param value The bytes for dateField to set.
       * @return This builder for chaining.
       */
      public Builder setDateFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        valueCase_ = 6;
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:models.publication.PublicationField)
    }

    // @@protoc_insertion_point(class_scope:models.publication.PublicationField)
    private static final models.publication.PublicationOuterClass.PublicationField DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new models.publication.PublicationOuterClass.PublicationField();
    }

    public static models.publication.PublicationOuterClass.PublicationField getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PublicationField>
        PARSER = new com.google.protobuf.AbstractParser<PublicationField>() {
      @java.lang.Override
      public PublicationField parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PublicationField(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PublicationField> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PublicationField> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public models.publication.PublicationOuterClass.PublicationField getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PublicationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:models.publication.Publication)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .models.publication.PublicationField fields = 1;</code>
     */
    java.util.List<models.publication.PublicationOuterClass.PublicationField> 
        getFieldsList();
    /**
     * <code>repeated .models.publication.PublicationField fields = 1;</code>
     */
    models.publication.PublicationOuterClass.PublicationField getFields(int index);
    /**
     * <code>repeated .models.publication.PublicationField fields = 1;</code>
     */
    int getFieldsCount();
    /**
     * <code>repeated .models.publication.PublicationField fields = 1;</code>
     */
    java.util.List<? extends models.publication.PublicationOuterClass.PublicationFieldOrBuilder> 
        getFieldsOrBuilderList();
    /**
     * <code>repeated .models.publication.PublicationField fields = 1;</code>
     */
    models.publication.PublicationOuterClass.PublicationFieldOrBuilder getFieldsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code models.publication.Publication}
   */
  public static final class Publication extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:models.publication.Publication)
      PublicationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Publication.newBuilder() to construct.
    private Publication(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Publication() {
      fields_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Publication();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Publication(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                fields_ = new java.util.ArrayList<models.publication.PublicationOuterClass.PublicationField>();
                mutable_bitField0_ |= 0x00000001;
              }
              fields_.add(
                  input.readMessage(models.publication.PublicationOuterClass.PublicationField.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          fields_ = java.util.Collections.unmodifiableList(fields_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return models.publication.PublicationOuterClass.internal_static_models_publication_Publication_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return models.publication.PublicationOuterClass.internal_static_models_publication_Publication_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              models.publication.PublicationOuterClass.Publication.class, models.publication.PublicationOuterClass.Publication.Builder.class);
    }

    public static final int FIELDS_FIELD_NUMBER = 1;
    private java.util.List<models.publication.PublicationOuterClass.PublicationField> fields_;
    /**
     * <code>repeated .models.publication.PublicationField fields = 1;</code>
     */
    @java.lang.Override
    public java.util.List<models.publication.PublicationOuterClass.PublicationField> getFieldsList() {
      return fields_;
    }
    /**
     * <code>repeated .models.publication.PublicationField fields = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends models.publication.PublicationOuterClass.PublicationFieldOrBuilder> 
        getFieldsOrBuilderList() {
      return fields_;
    }
    /**
     * <code>repeated .models.publication.PublicationField fields = 1;</code>
     */
    @java.lang.Override
    public int getFieldsCount() {
      return fields_.size();
    }
    /**
     * <code>repeated .models.publication.PublicationField fields = 1;</code>
     */
    @java.lang.Override
    public models.publication.PublicationOuterClass.PublicationField getFields(int index) {
      return fields_.get(index);
    }
    /**
     * <code>repeated .models.publication.PublicationField fields = 1;</code>
     */
    @java.lang.Override
    public models.publication.PublicationOuterClass.PublicationFieldOrBuilder getFieldsOrBuilder(
        int index) {
      return fields_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < fields_.size(); i++) {
        output.writeMessage(1, fields_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < fields_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, fields_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof models.publication.PublicationOuterClass.Publication)) {
        return super.equals(obj);
      }
      models.publication.PublicationOuterClass.Publication other = (models.publication.PublicationOuterClass.Publication) obj;

      if (!getFieldsList()
          .equals(other.getFieldsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFieldsCount() > 0) {
        hash = (37 * hash) + FIELDS_FIELD_NUMBER;
        hash = (53 * hash) + getFieldsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static models.publication.PublicationOuterClass.Publication parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static models.publication.PublicationOuterClass.Publication parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static models.publication.PublicationOuterClass.Publication parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static models.publication.PublicationOuterClass.Publication parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static models.publication.PublicationOuterClass.Publication parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static models.publication.PublicationOuterClass.Publication parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static models.publication.PublicationOuterClass.Publication parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static models.publication.PublicationOuterClass.Publication parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static models.publication.PublicationOuterClass.Publication parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static models.publication.PublicationOuterClass.Publication parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static models.publication.PublicationOuterClass.Publication parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static models.publication.PublicationOuterClass.Publication parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(models.publication.PublicationOuterClass.Publication prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code models.publication.Publication}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:models.publication.Publication)
        models.publication.PublicationOuterClass.PublicationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return models.publication.PublicationOuterClass.internal_static_models_publication_Publication_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return models.publication.PublicationOuterClass.internal_static_models_publication_Publication_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                models.publication.PublicationOuterClass.Publication.class, models.publication.PublicationOuterClass.Publication.Builder.class);
      }

      // Construct using models.publication.PublicationOuterClass.Publication.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFieldsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (fieldsBuilder_ == null) {
          fields_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          fieldsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return models.publication.PublicationOuterClass.internal_static_models_publication_Publication_descriptor;
      }

      @java.lang.Override
      public models.publication.PublicationOuterClass.Publication getDefaultInstanceForType() {
        return models.publication.PublicationOuterClass.Publication.getDefaultInstance();
      }

      @java.lang.Override
      public models.publication.PublicationOuterClass.Publication build() {
        models.publication.PublicationOuterClass.Publication result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public models.publication.PublicationOuterClass.Publication buildPartial() {
        models.publication.PublicationOuterClass.Publication result = new models.publication.PublicationOuterClass.Publication(this);
        int from_bitField0_ = bitField0_;
        if (fieldsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            fields_ = java.util.Collections.unmodifiableList(fields_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.fields_ = fields_;
        } else {
          result.fields_ = fieldsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof models.publication.PublicationOuterClass.Publication) {
          return mergeFrom((models.publication.PublicationOuterClass.Publication)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(models.publication.PublicationOuterClass.Publication other) {
        if (other == models.publication.PublicationOuterClass.Publication.getDefaultInstance()) return this;
        if (fieldsBuilder_ == null) {
          if (!other.fields_.isEmpty()) {
            if (fields_.isEmpty()) {
              fields_ = other.fields_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFieldsIsMutable();
              fields_.addAll(other.fields_);
            }
            onChanged();
          }
        } else {
          if (!other.fields_.isEmpty()) {
            if (fieldsBuilder_.isEmpty()) {
              fieldsBuilder_.dispose();
              fieldsBuilder_ = null;
              fields_ = other.fields_;
              bitField0_ = (bitField0_ & ~0x00000001);
              fieldsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFieldsFieldBuilder() : null;
            } else {
              fieldsBuilder_.addAllMessages(other.fields_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        models.publication.PublicationOuterClass.Publication parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (models.publication.PublicationOuterClass.Publication) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<models.publication.PublicationOuterClass.PublicationField> fields_ =
        java.util.Collections.emptyList();
      private void ensureFieldsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          fields_ = new java.util.ArrayList<models.publication.PublicationOuterClass.PublicationField>(fields_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          models.publication.PublicationOuterClass.PublicationField, models.publication.PublicationOuterClass.PublicationField.Builder, models.publication.PublicationOuterClass.PublicationFieldOrBuilder> fieldsBuilder_;

      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public java.util.List<models.publication.PublicationOuterClass.PublicationField> getFieldsList() {
        if (fieldsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fields_);
        } else {
          return fieldsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public int getFieldsCount() {
        if (fieldsBuilder_ == null) {
          return fields_.size();
        } else {
          return fieldsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public models.publication.PublicationOuterClass.PublicationField getFields(int index) {
        if (fieldsBuilder_ == null) {
          return fields_.get(index);
        } else {
          return fieldsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public Builder setFields(
          int index, models.publication.PublicationOuterClass.PublicationField value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.set(index, value);
          onChanged();
        } else {
          fieldsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public Builder setFields(
          int index, models.publication.PublicationOuterClass.PublicationField.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.set(index, builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public Builder addFields(models.publication.PublicationOuterClass.PublicationField value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.add(value);
          onChanged();
        } else {
          fieldsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public Builder addFields(
          int index, models.publication.PublicationOuterClass.PublicationField value) {
        if (fieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldsIsMutable();
          fields_.add(index, value);
          onChanged();
        } else {
          fieldsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public Builder addFields(
          models.publication.PublicationOuterClass.PublicationField.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.add(builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public Builder addFields(
          int index, models.publication.PublicationOuterClass.PublicationField.Builder builderForValue) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.add(index, builderForValue.build());
          onChanged();
        } else {
          fieldsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public Builder addAllFields(
          java.lang.Iterable<? extends models.publication.PublicationOuterClass.PublicationField> values) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, fields_);
          onChanged();
        } else {
          fieldsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public Builder clearFields() {
        if (fieldsBuilder_ == null) {
          fields_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          fieldsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public Builder removeFields(int index) {
        if (fieldsBuilder_ == null) {
          ensureFieldsIsMutable();
          fields_.remove(index);
          onChanged();
        } else {
          fieldsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public models.publication.PublicationOuterClass.PublicationField.Builder getFieldsBuilder(
          int index) {
        return getFieldsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public models.publication.PublicationOuterClass.PublicationFieldOrBuilder getFieldsOrBuilder(
          int index) {
        if (fieldsBuilder_ == null) {
          return fields_.get(index);  } else {
          return fieldsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public java.util.List<? extends models.publication.PublicationOuterClass.PublicationFieldOrBuilder> 
           getFieldsOrBuilderList() {
        if (fieldsBuilder_ != null) {
          return fieldsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fields_);
        }
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public models.publication.PublicationOuterClass.PublicationField.Builder addFieldsBuilder() {
        return getFieldsFieldBuilder().addBuilder(
            models.publication.PublicationOuterClass.PublicationField.getDefaultInstance());
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public models.publication.PublicationOuterClass.PublicationField.Builder addFieldsBuilder(
          int index) {
        return getFieldsFieldBuilder().addBuilder(
            index, models.publication.PublicationOuterClass.PublicationField.getDefaultInstance());
      }
      /**
       * <code>repeated .models.publication.PublicationField fields = 1;</code>
       */
      public java.util.List<models.publication.PublicationOuterClass.PublicationField.Builder> 
           getFieldsBuilderList() {
        return getFieldsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          models.publication.PublicationOuterClass.PublicationField, models.publication.PublicationOuterClass.PublicationField.Builder, models.publication.PublicationOuterClass.PublicationFieldOrBuilder> 
          getFieldsFieldBuilder() {
        if (fieldsBuilder_ == null) {
          fieldsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              models.publication.PublicationOuterClass.PublicationField, models.publication.PublicationOuterClass.PublicationField.Builder, models.publication.PublicationOuterClass.PublicationFieldOrBuilder>(
                  fields_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          fields_ = null;
        }
        return fieldsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:models.publication.Publication)
    }

    // @@protoc_insertion_point(class_scope:models.publication.Publication)
    private static final models.publication.PublicationOuterClass.Publication DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new models.publication.PublicationOuterClass.Publication();
    }

    public static models.publication.PublicationOuterClass.Publication getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Publication>
        PARSER = new com.google.protobuf.AbstractParser<Publication>() {
      @java.lang.Override
      public Publication parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Publication(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Publication> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Publication> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public models.publication.PublicationOuterClass.Publication getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_models_publication_PublicationField_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_models_publication_PublicationField_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_models_publication_Publication_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_models_publication_Publication_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/proto/publication.proto\022\022mode" +
      "ls.publication\"\240\001\n\020PublicationField\022\021\n\tf" +
      "ieldName\030\001 \001(\t\022\026\n\014companyField\030\002 \001(\tH\000\022\024" +
      "\n\nvalueField\030\003 \001(\001H\000\022\023\n\tdropField\030\004 \001(\001H" +
      "\000\022\030\n\016variationField\030\005 \001(\001H\000\022\023\n\tdateField" +
      "\030\006 \001(\tH\000B\007\n\005value\"C\n\013Publication\0224\n\006fiel" +
      "ds\030\001 \003(\0132$.models.publication.Publicatio" +
      "nFieldb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_models_publication_PublicationField_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_models_publication_PublicationField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_models_publication_PublicationField_descriptor,
        new java.lang.String[] { "FieldName", "CompanyField", "ValueField", "DropField", "VariationField", "DateField", "Value", });
    internal_static_models_publication_Publication_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_models_publication_Publication_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_models_publication_Publication_descriptor,
        new java.lang.String[] { "Fields", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
